# Generated by Django 5.2.17 on 2026-09-23 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_visitrequest'),
        ('properties', '0005_property_property_status_listing_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('FRAUD', 'Fraud'), ('INACCURATE', 'Inaccurate information'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_created_idx'), models.Index(fields=['property', 'status'], name='report_property_status_idx'), models.Index(fields=['reported_user', 'status'], name='report_user_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('reported_user__isnull', True)), models.Q(('property__isnull', True), ('reported_user__isnull', False)), _connector='OR'), name='report_exactly_one_target'), models.CheckConstraint(condition=models.Q(('reported_user__isnull', True), models.Q(('reporter', models.F('reported_user')), _negated=True), _connector='OR'), name='reporter_cannot_report_self')],
            },
        ),
    ]
