# Generated by Django 5.2.17 on 2026-09-23 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_report'),
        ('properties', '0005_property_property_status_listing_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('FAKE_LISTING', 'Fake listing'), ('WRONG_PRICE', 'Wrong price'), ('PROPERTY_RENTED', 'Property already rented'), ('MISLEADING_PHOTOS', 'Misleading photos'), ('SCAM', 'Scam'), ('OTHER', 'Other')], max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ACTION_TAKEN', 'Action taken')], db_index=True, default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reports', to='properties.property')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='prop_report_status_created_idx'), models.Index(fields=['property', 'status'], name='pr_property_status_idx'), models.Index(fields=['reported_by', '-created_at'], name='pr_user_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'REVIEWED'))), fields=('property', 'reported_by', 'reason'), name='active_property_report_unique')],
            },
        ),
    ]
