# Generated by Django 5.2.17 on 2026-09-23 14:23

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='property_type_name_ci_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='property_type_slug_ci_uniq')],
            },
        ),
    ]
