# Generated by Django 5.2.17 on 2026-09-23 14:41

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('RENTED', 'Rented'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', max_length=20)),
                ('listing_type', models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale')], db_index=True, max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Utilisez un code devise ISO en trois lettres majuscules.')])),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('area_unit', models.CharField(choices=[('SQM', 'Square metres'), ('SQFT', 'Square feet')], default='SQM', max_length=8)),
                ('furnished', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'status'], name='property_owner_status_idx'), models.Index(fields=['property_type', 'status'], name='property_type_status_idx'), models.Index(fields=['location', 'status'], name='property_location_status_idx'), models.Index(fields=['status', 'created_at'], name='property_status_created_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='property_slug_ci_unique'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='property_price_nonnegative'), models.CheckConstraint(condition=models.Q(('bathrooms__isnull', True), ('bathrooms__gte', 0), _connector='OR'), name='property_bathrooms_nonnegative'), models.CheckConstraint(condition=models.Q(('area__isnull', True), ('area__gte', 0), _connector='OR'), name='property_area_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), _connector='OR'), name='property_coordinates_valid'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('published_at__isnull', True), ('expires_at__gt', models.F('published_at')), _connector='OR'), name='property_expiry_after_publish')],
            },
        ),
    ]
