# Generated by Django 5.2.17 on 2026-09-23 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2048)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['property', 'sort_order'], name='property_image_sort_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'sort_order'), name='property_image_order_unique'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('property',), name='property_single_primary_image')],
            },
        ),
    ]
