# Generated by Django 5.2.17 on 2026-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('MONTH', 'Month'), ('YEAR', 'Year')], db_index=True, default='MONTH', max_length=8, null=True),
        ),
    ]
