# Generated by Django 5.2.17 on 2026-09-22 20:52

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('type', models.CharField(choices=[('COUNTRY', 'Country'), ('DEPARTMENT', 'Department'), ('CITY', 'City'), ('COMMUNE', 'Commune'), ('NEIGHBORHOOD', 'Neighborhood'), ('AREA', 'Area')], db_index=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.location')),
            ],
            options={
                'ordering': ('type', 'name'),
                'indexes': [models.Index(fields=['type', 'is_active'], name='location_type_active_idx'), models.Index(fields=['parent', 'is_active'], name='location_parent_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('parent'), name='location_sibling_slug_ci_uniq'), models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), condition=models.Q(('parent__isnull', True)), name='location_root_slug_ci_uniq'), models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='location_not_own_parent'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), _connector='OR'), name='location_coordinates_valid')],
            },
        ),
    ]
