# Generated by Django 5.2.17 on 2026-09-23 18:46

from django.db import migrations, models


def create_default_free_plan(apps, schema_editor):
    Plan = apps.get_model("monetization", "Plan")
    Plan.objects.using(schema_editor.connection.alias).get_or_create(
        code="FREE",
        defaults={
            "name": "Free",
            "description": "Plan de démarrage gratuit.",
            "price": 0,
            "currency": "USD",
            "is_active": True,
            "max_active_properties": 2,
            "can_promote_properties": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_promote_properties',
            field=models.BooleanField(default=False, help_text='Autorise les propriétaires abonnés à créer des promotions de propriétés.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_active_properties',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximal d’annonces actives. Laisser vide pour une limite illimitée.', null=True),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('max_active_properties__isnull', True), ('max_active_properties__gte', 0), _connector='OR'), name='plan_property_limit_nonnegative'),
        ),
        migrations.RunPython(create_default_free_plan, migrations.RunPython.noop),
    ]
