# Generated by Django 5.2.17 on 2026-10-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0002_plan_can_promote_properties_and_more'),
        ('properties', '0007_property_rental_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_exactly_one_purchase',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property', '-created_at'], name='payment_property_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('promotion__isnull', True), ('property__isnull', True), ('subscription__isnull', False)), models.Q(('promotion__isnull', False), ('property__isnull', True), ('subscription__isnull', True)), models.Q(('promotion__isnull', True), ('property__isnull', False), ('subscription__isnull', True)), _connector='OR'), name='payment_exactly_one_purchase'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False), ('status', 'PAID')), fields=('property',), name='unique_paid_payment_per_property'),
        ),
    ]
