# Generated by Django 5.2.17 on 2026-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0003_remove_payment_payment_exactly_one_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
