# Generated by Django 5.2.17 on 2026-09-23 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROPERTY_APPROVED', 'Property approved'), ('PROPERTY_REJECTED', 'Property rejected'), ('NEW_INQUIRY', 'New inquiry'), ('NEW_VISIT_REQUEST', 'New visit request'), ('VISIT_ACCEPTED', 'Visit accepted'), ('VISIT_REJECTED', 'Visit rejected'), ('NEW_VERIFICATION', 'New owner verification'), ('PROPERTY_REPORTED', 'Property reported')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read_created_idx'), models.Index(fields=['user', '-created_at'], name='notification_user_created_idx')],
            },
        ),
    ]
