# Generated by Django 5.2.17 on 2026-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROPERTY_APPROVED', 'Property approved'), ('PROPERTY_REJECTED', 'Property rejected'), ('NEW_INQUIRY', 'New inquiry'), ('NEW_VISIT_REQUEST', 'New visit request'), ('VISIT_ACCEPTED', 'Visit accepted'), ('VISIT_REJECTED', 'Visit rejected'), ('NEW_VERIFICATION', 'New owner verification'), ('PROPERTY_REPORTED', 'Property reported'), ('NEW_OWNER_REQUEST', 'New owner request'), ('OWNER_REQUEST_APPROVED', 'Owner request approved'), ('OWNER_REQUEST_REJECTED', 'Owner request rejected')], db_index=True, max_length=32),
        ),
    ]
